name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths:
      - './trafficlights-cli/**'
  pull_request:
    branches: [ master ]
    paths:
      - './trafficlights-cli/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B clean verify --file trafficlights-cli
